#!/usr/bin/env bash
DIR=$HOME/.config/hypr/wallpapers
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}
#this is a random number between 1 and 3 and is used to select the transition type below
SELECTED_TRANSITION_TYPE=$((1 + RANDOM % 3))


if [ "$SELECTED_TRANSITION_TYPE" -eq 1 ]; then
    swww img --transition-type=grow --transition-pos=0.854,0.977 --transition-step=90 ${DIR}/${RANDOMPICS}
elif [ "$SELECTED_TRANSITION_TYPE" -eq 2 ]; then
    swww img --transition-type=wipe --transition-pos=0.854,0.977 --transition-step=90 ${DIR}/${RANDOMPICS}
else
    swww img --transition-type=outer --transition-pos=0.854,0.977 --transition-step=90 ${DIR}/${RANDOMPICS}
fi  
notify-send "${RANDOMPICS}"
